support/dynamic_loader/dynamic_library.cpp
support/dynamic_loader/dynamic_library.h
support/log/log.h

DynamicLibrary and its child classes should have virtual dtor

Fix warnings when build on Linux

---

support/containers/allocator.h
support/entry/entry.cpp
vulkan_helpers/vulkan_application.cpp

We were calling allocator_->free() on an AllocationToken, instead
of deleting it properly. This meant that the iterator
was not getting deleted it was just getting zeroed.
In windows, debug, checked iterators are a lot more than just a
POD type, deleting a checked iterator can modify other iterators
to the same object. (They are internally a big linked list
of all iterators to the same object).

Fix a bug in VulkanArena.

---

vulkan_helpers/vulkan_application.cpp
vulkan_helpers/vulkan_application.h

I used this in my own experimentation, e.g. in the tiny_compute_glsl example in 
https://github.com/dneto0/vulkan_test_applications/tree/tiny_compute_read_workgroup_size_defaulted_to_1
I didn't add support for specialization in graphics pipelines.

Enable spec constant overrides for compute shaders

---

vulkan_helpers/helper_functions.cpp

This fixes a null pointer exception in vkGetDevice queue on an AMD card.

Fix queueCreateInfoCount for vkCreateDevice

---

application_sandbox/copy_image_2d3d/main.cpp
application_sandbox/draw_indexed_indirect_count/main.cpp
application_sandbox/khr_image_format_list/main.cpp
application_sandbox/multigpu_particles/main.cpp
application_sandbox/render_3d_image/main.cpp
application_sandbox/sample_application_framework/sample_application.h
gapid_tests/command_buffer_tests/BufferImageCopy_test/main.cpp
gapid_tests/command_buffer_tests/SetDepthBias_test/main.cpp
gapid_tests/command_buffer_tests/SetLineWidthAndBlendConstants_test/wide_lines.cpp
gapid_tests/command_buffer_tests/vkCmdBlitImage_test/main.cpp
gapid_tests/command_buffer_tests/vkCmdCopyImage_test/main.cpp
gapid_tests/command_buffer_tests/vkCmdNextSubpass_test/main.cpp
gapid_tests/command_buffer_tests/vkCmdResolveImage_test/main.cpp
gapid_tests/command_buffer_tests/vkCmdSetDepthBounds_test/main.cpp
gapid_tests/command_buffer_tests/vkCmdUpdateBuffer_test/main.cpp
gapid_tests/extension_tests/VK_NV_dedicated_allocation_test/main.cpp
gapid_tests/extension_tests/VK_NV_dedicated_allocation_test/main_no_dedicated.cpp
gapid_tests/resource_creation_tests/CreateDestroyQueryPool_test/pipeline_statistic.cpp
gapid_tests/resource_creation_tests/CreateDestroySampler_test/unnormalized.cpp
vulkan_helpers/helper_functions.cpp
vulkan_helpers/helper_functions.h
vulkan_helpers/vulkan_application.cpp
vulkan_helpers/vulkan_application.h

Instance extension list comes before the device extensions in
constructors and functions when both are specified.
Also changes all direct text extensions ("VK_KHR_draw_indirect_count")
to use the standard #define (VK_KHR_DRAW_INDIRECT_COUNT_EXTENSION_NAME)
for future grepping.
Clang format also rearranged some random code here and there.

Add instance extensions to application framework

---

application_sandbox/sample_application_framework/sample_application.h
support/entry/entry.cpp
support/entry/entry.h
vulkan_helpers/helper_functions.cpp
vulkan_helpers/helper_functions.h
vulkan_helpers/vulkan_application.cpp
vulkan_helpers/vulkan_application.h

This adds --load-pipeline-cache=<file> --write-pipeline-cache=<file>
that all sample applications will use to read/write pipeline caches.

Added optional load/save pipeline cache functionality to Applications.

---

application_sandbox/create_renderpass2/main.cpp
application_sandbox/depth_stencil_resolve/main.cpp

create_renderpass2 and depth_stencil_resolve weren't including
VK_KHR_get_physical_device_properties2 in their isntance extensions in
spite of it being required for VK_KHR_multiview (which they both use).
Fix this by adding get_physical_device_properties2 to their instance
extensions.

Fix validation error for samples using VK_KHR_multiview.

---

application_sandbox/shader_float16_int8/main.cpp
application_sandbox/storage_8bit/main.cpp

The two applications being changed, shader_float16_int8 and storage_8bit, don't use storagePushConstant8 but request support when creating a device. This change allows these applications to work on platforms that have the required 8bit storage support but don't support storagePushConstant8.

Remove storagePushConstant8 from apps that don't used it

---

vulkan_helpers/helper_functions.h

This bug was causing compilation for the repo to fail. This should fix it.

Fix bug in GetMemoryIndex

---

vulkan_helpers/vulkan_application.cpp
vulkan_helpers/vulkan_application.h

This adds support for adjusting depth clamp and depth bias parameters when building pipelines.

Expose additional rasterization state parameters

---

vulkan_helpers/vulkan_application.h

Fixes a mistake with https://github.com/google/vulkan_test_applications/pull/172
Currently Push Constants cannot be used with vulkan::PipelineLayout because it can only be created via CreatePipelineLayout which doesn't support the optional parameter for VkPushConstantRanges.

Add Push Constants to CreatePipelineLayout

---

vulkan_helpers/vulkan_application.h

The PipelineLayout constructor uses a vector of VkPushConstantRange. However, it wasn't declared with the required allocator and the program crashes whenever push constants are used with CreatePipelineLayout.
This PR fixes the problem.

Fix missing allocator in PipelineLayout constructor

---

application_sandbox/conditional_rendering/cube.frag
application_sandbox/conditional_rendering/main.cpp
vulkan_helpers/buffer_frame_data.h

- Simplify fragment shader, value in colorScale should be 0 or 1
- Update dispatch buffer value to 0
- Force update dispatch buffer update. Since it's value is updated
by the GPU, values might not be up to date when UpdateBuffer does
a comparison to decide whether to update.
- Add proper dstAccessMask bits for conditional rendering buffer

Conditional rendering patch

---

vulkan_helpers/structs.cpp

The Vulkan enums that ended in BEGIN_RANGE, END_RANGE, RANGE_SIZE were removed in Vulkan-Headers 1.2.140. This caused some issues when this repo was used inside another repo that had already moved past 1.2.140. This change updates to 1.2.165 (the latest) and fixes the removed enums.

Update Vulkan-Headers to 1.2.165

---

application_sandbox/overlapping_frames/README.md
application_sandbox/overlapping_frames/main.cpp

See commits one by one for an easier review.
The clang-formatting touches almost all lines, leading to a big diff.
It's mostly moving code around and editing comments. The only significant semantics difference is to lower the minimal number of swapchain images from three to two: I double checked that this is enough, and that the sample does work when the app allocates only two swapchain images.

Cleanup of overlapping frames sample

---

vulkan_helpers/helper_functions.cpp

The VkPhysicalDeviceFloatControlsPropertiesKHR struct is not valid when passed to vkCreateDevice, its only to be used as a query to vkGetPhysicalDeviceProperties2. This was picked as a validation error with some recent version of the validation layers.

Remove invalid pNext entry from vkCreateDevice.

---

application_sandbox/sample_application_framework/sample_application.h
application_sandbox/stencil/main.cpp
vulkan_helpers/helper_functions.h

This adds a helper function, GetSupportedDepthStencilFormat, that can be used by any application. The sample application has been changed to make use of this.
Additionally, the stencil sample has been updated to make use of the built-in stencil support.

Add a helper function to find a supported depth/stencil format.

---

application_sandbox/async_compute/main.cpp
application_sandbox/sample_application_framework/sample_application.h

In async_compute test application, async thread runner continues to
submit work after vkDeviceWaitIdle is resolved. This change fixes
this behaviour by terminating the async thread before wait idle.

Fix async_compute submit after device wait idle

---

application_sandbox/transform_feedback/main.cpp

Fixes the vkCmdPipeline error that this command cannot be recorded when TransfromFeedback is active

Fixes the vkCmdPipeline error 

---

support/android_native_app_glue/CMakeLists.txt

From issue #210 , the usage of COPY_ONLY is incorrect in newer versions of cmake. This has been change to COPYONLY. I ran the two docker builds (linux and android) with this change and both build without issue.

Fix configure_files parameter, replacing COPY_ONLY with COPYONLY

---

.github/workflows/pull_request.yml
cmake/build_apk.cmake

Some recent change to the ubuntu-18.04 VM broke the python setup. This change fixes the build via the following:
* Add a `uses` to setup python, this seems to be the recommended way to get python installed.
* Changed the cmake process to find Python3 instead of the deprecated PythonInterp, this will now properly pick up the python install via the additional `uses`.

Update action workflow due to recent python changes.

---

support/entry/entry.cpp
support/entry/entry.h

Closing the application on Win32 would lead to a crash due to a VK_ERROR_OUT_OF_DATE when doing a present. This PR adds support for properly shutting down to avoid the crash. This also allows for proper memory leak detection.
Additionally, some window style properties (resize, maximize) were removed to avoid other scenarios where an VK_ERROR_OUT_OF_DATE is generated.

Add support for gracefully closing applications on Win32.

---

application_sandbox/async_compute/main.cpp
application_sandbox/compute_particles/main.cpp
application_sandbox/multigpu_particles/main.cpp
application_sandbox/timeline_semaphore_cross_queue/main.cpp
vulkan_helpers/buffer_frame_data.h

This PR adds support for explicitly specifying the offset alignment used in creating a BufferFrameData object. If not specified, the offset alignment will continue to be the maximum one allowed by the Vulkan spec (i.e. kMaxOffsetAlignment).
The set of optional of parameters (device_mask, queue_family_index and now offset_alignment) used when creating a BufferFrameData object have been refactored into a BufferFrameDataOptions struct to avoid having too many integer based, default value arguments in the constructor.

Add support for specifying offset alignment in BufferFrameData.

---

vulkan_helpers/vulkan_application.cpp
vulkan_helpers/vulkan_application.h

Change VkBuffer::flush so that it adheres to the alignment requirements of VkMappedMemoryRange for offset and size.
This is now an issue because explicit offset alignments can be used (See #218). The previous offset alignment values where always kMaxOffsetAlignment which matches kMaxNonCoherentAtomSize.

Enforce nonCoherentAtomSize rules when flushing buffers.

---

application_sandbox/sample_application_framework/sample_application.h
vulkan_helpers/vulkan_application.cpp
vulkan_helpers/vulkan_application.h

This is a simplified version of #178. This leaves the old `VulkanApplication` constructor in addition to the new `VulkanApplicationOptions` constructor. This avoids needing for a monolithic update to move all the `VulkanApplication` uses to use the new `VulkanApplicationOptions` constructor.

Add option struct to clean up VulkanApplication parameter list (simplified)

---

application_sandbox/format_feature_flags2/main.cpp
application_sandbox/sample_application_framework/sample_application.h

SetVulkanApiVersion was not actually setting anything. Also fixed a sample that was using the old EnableVulkan11 method.

Fix SetVulkanApiVersion

---

vulkan_helpers/helper_functions.cpp

These structs are added in Vulkan 1.1, but the samples are still using Vulkan 1.0 by default, causing validation warnings.
This change only includes the structs in the pNext chain when they are being activated.

Fix validation warning about unsupported pNext structs
